- name: Configure Nginx and PHP
  block:
    - name: Stop apache2
      ansible.builtin.service:
        name: apache2.service
        state: stopped
        enabled: false

    - name: Create and change ownership of a directory data
      ansible.builtin.file:
        path: "{{ initapps_data_path }}"
        state: directory
        # recurse: yes
        owner: "{{ initapps_user }}"
        group: "{{ initapps_user }}"
        mode: "0755"

    - name: Change conf nginx
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: "Restart nginx"

    - name: Check if dir site-available exist
      ansible.builtin.stat:
        path: "/etc/nginx/sites-available/"
      register: dir_stat

    - name: Add joomla.conf in nginx
      ansible.builtin.template:
        src: templates/joomla.conf.j2
        dest: /etc/nginx/sites-available/joomla.conf
        mode: "0644"
      notify: "Restart nginx"
      when: dir_stat.stat.exists

    - name: Create a symbolic link to joomla.conf
      ansible.builtin.file:
        src: /etc/nginx/sites-available/joomla.conf
        dest: /etc/nginx/sites-enabled/joomla.conf
        owner: root
        group: root
        state: link
      when: dir_stat.stat.exists

    - name: Change default.conf nginx
      ansible.builtin.template:
        src: templates/joomla.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: "Restart nginx"
      when: not dir_stat.stat.exists

    # - name: Copy index file with owner and permissions
    #  ansible.builtin.copy:
    #    src: ./files/index.php
    #    dest: "{{ initapps_data_path }}/index.php"
    #    owner: "{{ initapps_user }}"
    #    group: "{{ initapps_user }}"
    #    mode: '0644'

    - name: Copy fast-cgi file
      ansible.builtin.copy:
        src: ./files/fastcgi-php-full.conf
        dest: "/etc/nginx/fastcgi_php_full.conf"
        owner: "root"
        group: "root"
        mode: '0644'
