---
# tasks file for php
- name: PHP installation
  block:
    - name: Install install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        state: present

    - name: Add Php repository on Debian/Ubuntu
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: Apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install PHP on Debian/Ubuntu present version
      ansible.builtin.package:
        name:
          - php
          - php-mysql
          - php{{ php_version }}-fpm
          - php-xml
          - php-json
          - php-zip
          - php-gd
          - php{{ php_version }}-common
          - libapache2-mod-php
          - php{{ php_version }}-cli
          - php{{ php_version }}-mysql
          - php{{ php_version }}-gmp
          - php{{ php_version }}-curl
          - php{{ php_version }}-intl
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-xmlrpc
          - php{{ php_version }}-gd
          - php{{ php_version }}-xml
          - php{{ php_version }}-zip
        state: present
        policy_rc_d: 101

    - name: Started and enabled php
      ansible.builtin.service:
        name: php{{ php_version }}-fpm
        state: started
        enabled: true
